const SCRAPER_TYPES = {
    PUPPETEER: 'PUPPETEER_SCRAPER',
    API: 'API_SCRAPER',
    OFFICIAL_API: 'OFFICIAL_API_SCRAPER',
    DETAILED: 'DETAILED_SCRAPER'
};


module.exports = SCRAPER_TYPES;